# Generated by Django 4.2 on 2023-07-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Yazı',
                'verbose_name_plural': 'Yazılar',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
