# Generated by Django 4.2 on 2023-07-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_blog_isim_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='isim',
        ),
    ]
