# Generated by Django 4.2 on 2023-07-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.kategori'),
        ),
    ]
