# Generated by Django 4.2 on 2023-07-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_altkategori_blog_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ornek',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ornegim', to='posts.kategori'),
        ),
    ]
