# Generated by Django 4.2 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_id'),
        ('posts', '0011_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dislike',
            field=models.ManyToManyField(to='user.profile'),
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(related_name='beğeniler', to='user.profile'),
        ),
    ]
