# Generated by Django 4.2 on 2023-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_follow_alter_profile_follower'),
        ('posts', '0012_blog_dislike_blog_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='goruntulenme', to='user.profile'),
        ),
    ]
