# Generated by Django 4.2 on 2023-07-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_ipmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='goruntulenme', to='posts.ipmodel'),
        ),
    ]
