# Generated by Django 4.2 on 2023-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Merhaba ben bir blog yazarıyım', verbose_name='Hakkımda'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/default-profile.jpeg', upload_to='profiles/', verbose_name='Profil Resmi'),
        ),
    ]
